/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Buble.ce': typeof import('./src/components/Buble.ce.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
  }
}
