/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    'Chat.ce': typeof import('./src/components/Chat.ce.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    Widget: typeof import('./src/components/Widget.vue')['default']
    'Widget.ce': typeof import('./src/components/Widget.ce.vue')['default']
  }
}
